language: python
python:
  - 2.6
  - 2.7
  - 3.2
install:
  - python setup.py install
  - pip install coverage
script: coverage run setup.py test
after_success:
  - pip install coveralls
  - coveralls
